AWSTemplateFormatVersion: '2024-04-11'
Description: CloudComp Assignment 3
Parameters:
  GitHubRepo:
    Type: String

  GitHubBranch:
    Type: String

  GitHubToken:
    Type: String

  GitHubUser:
    Type: String

Resources:
  PhotoBucket:
    Type: AWS::S3::Bucket

  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      OwnershipControls:
        Rules:
        - ObjectOwnership: BucketOwnerPreferred
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  IndexPhotosLambdaRole:
    Type: AWS::IAM::Role

  IndexPhotos:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          import json

          def lambda_handler(event, context):
              print(json.dumps(event))

              return {
                statusCode': 200,
                'body': json.dumps('Hello from search-photos!')
              }

      Handler: index.handler
      Runtime: python3.12
      Role: !GetAtt IndexPhotosLambdaRole.Arn
  
  SearchPhotosLambdaRole:
    Type: AWS::IAM::Role

  SearchPhotos:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          import json

          def lambda_handler(event, context):
              print(json.dumps(event))

              return {
                statusCode': 200,
                'body': json.dumps('Hello from search-photos!')
              }

      Handler: index.handler
      Runtime: python3.12
      Role: !GetAtt SearchPhotosLambdaRole.Arn